DIRNAME := $(shell basename $(realpath .))
SHELL := /bin/bash

FAILURE := "\e[31mFAILED\e[39m"
SUCCESS := "\e[32mOK\e[39m"
ERROR := "\e[41mERROR\e[49m"

.PHONY: all
all: $(DIRNAME).exe test

%.exe: %.c
	$(CC) -o $@ $<

%.exe: %.cpp
	$(CXX) -o $@ $<

.PHONY: clean
clean:
	@rm -fv *.exe

.PHONY: test
test: $(DIRNAME).exe
	@for input in $$(ls input* 2>/dev/null); do \
	  test=$${input#input}; \
	  test=$${test%.txt}; \
	  echo "Test case: $${test}: Running"; \
	  cat $${input} | \
	    ./$(DIRNAME).exe | \
	    diff <(sed -e '$$a\' /dev/stdin) <(sed -e '$$a\' output$${test}.txt); \
	  retval=$$?; \
	  echo -n "Test case: $${test}: "; \
	  case $${retval} in \
	  0) echo -e $(SUCCESS);; \
	  1) echo -e $(FAILURE);; \
	  *) echo -e $(ERROR);; \
	  esac; \
	done
